# Generated by Django 6.0.7 on 2026-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
