# Generated by Django 6.0.7 on 2026-07-23 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(help_text='Example: Toyota Hiace, Mercedes Sprinter, Box Truck', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
