# Generated by Django 6.0.7 on 2026-08-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='drivers_license_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/license/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='drivers/insurance/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/national_id/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/profile/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('CAR', 'Car'), ('MOTORCYCLE', 'Motorcycle'), ('BICYCLE', 'Bicycle'), ('SCOOTER', 'Scooter'), ('WALKING', 'Walking')], default='CAR', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inspection_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ownership_type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('COMPANY', 'Company Vehicle'), ('RENTAL', 'Rental'), ('BORROWED', 'Borrowed')], default='OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
