# Generated by Django 6.0.7 on 2026-07-17 12:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('goods_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('FOOD', 'Food'), ('GROCERIES', 'Groceries'), ('ELECTRONICS', 'Electronics'), ('CLOTHING', 'Clothing'), ('FURNITURE', 'Furniture'), ('MEDICINE', 'Medicine'), ('CONSTRUCTION', 'Construction Materials'), ('INDUSTRIAL', 'Industrial Equipment'), ('AGRICULTURE', 'Agricultural Products'), ('FRAGILE', 'Fragile Goods'), ('HAZARDOUS', 'Hazardous Goods'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('package_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_fragile', models.BooleanField(default=False)),
                ('pickup_address', models.TextField()),
                ('delivery_address', models.TextField()),
                ('priority', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('SAME_DAY', 'Same Day')], default='STANDARD', max_length=20)),
                ('estimated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DRIVER_ASSIGNED', 'Driver Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=30)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
