# Generated by Django 6.0.7 on 2026-07-20 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_code',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_qr_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_qr_used',
            field=models.BooleanField(default=False),
        ),
    ]
