# Generated by Django 6.0.7 on 2026-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_delivery_code_shipment_delivery_qr_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivery_code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
