# Generated by Django 6.0.7 on 2026-07-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='received_by_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
