# Generated by Django 6.0.7 on 2026-07-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipment_cancellation_reason_shipment_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pickup_code',
            field=models.CharField(blank=True, editable=False, max_length=6),
        ),
    ]
